<?php 
 return array (
  'WEBNAME' => '试用中心',
  'KEYWORD' => '每折网',
  'DESCRIPTION' => '',
  'AUTHKEY' => 'k0AeqqzwinAA7V71WrrEpei7',
  'DEFAULT_STYLE' => 'cloud3',
  'ERRORLOG' => '1',
  'ERRORLOG_SIZE' => '',
  'MAXLOGINFAILEDTIMES' => '0',
  'MINREFRESHTIME' => '3',
  'ADMIN_EMAIL' => '516985724@163.com',
  'MAIL_SERVER' => 'smtp.163.com',
  'MAIL_PORT' => '25',
  'MAIL_FROM' => '516985724@163.com',
  'MAIL_AUTH' => '1',
  'MAIL_USER' => '516985724@163.com',
  'MAIL_PASSWORD' => 'gmw_888908012714',
  'UPLOAD_MAXSIZE' => '256',
  'UPLOAD_ALLOWEXT' => 'jpg|jpeg|gif|bmp|png',
  'WATERMARK_MINWIDTH' => '300',
  'WATERMARK_MINHEIGHT' => '300',
  'WATERMARK_IMG' => 'mark.gif',
  'WATERMARK_PCT' => '60',
  'WATERMARK_QUALITY' => '80',
  'WATERMARK_POS' => '1',
  'MAIL_TYPE' => '1',
  'WATERMARK_ENABLE' => '1',
  'COOKIE_PREFIX' => 'Ofe',
  'SESSION_PREFIX' => 'AWQ',
  'SITE_WEB_TITLE' => '每折0元购',
  'SITE_WEB_LOGO' => '/uploadfile/2015/0112/20150112042610362.png',
  'SITE_WEB_COPYRIGHT' => 'adalways inc',
  'SITE_STATISTICAL_CODE' => '统计的代码',
  'SITE_WEB_ICP' => ' ICP',
  'WEIXIN_LOGO' => '/uploadfile/2016/0411/20160411114101987.jpg',
  'MERCHANT_GROUPNAME' => 'array (
  0 => 
  array (
    0 => \'钻石商家\',
  ),
)',
  'SITE_CONTACT_QQ1' => '88888888',
  'SITE_CONTACT_TEL' => '021-88888888',
  'SITE_CONTACT_EMAIL' => '88888888@qq.com',
  'SITE_CONTACT_ADDRESS' => '啥大幅放大法',
  'SITE_WEB_CLOSE' => '1',
  'SITE_WEB_CLOSE_CAUSE' => 'asdds',
  'SITE_CONTACT_CITY' => '2',
  'SITE_CONTACT_AREA' => '36',
  'IMG_URL' => 'fadsad',
  'IMG_TYPE' => '放大发生',
  'IMG_STATUS' => '0',
  'SETTING_REGISTER_EMAIL_ENABLE' => 'array (
  0 => \'1\',
)',
  'SETTING_REGISTER_SMS_ENABLE' => 'array (
  0 => \'1\',
  1 => \'2\',
)',
  'SITE_CONTACT_QQ2' => '4566542',
  'MERCHANT_IMAGE' => 'array (
  0 => \'./uploadfile/2014/1219/20141219021003382.jpg\',
)',
  'MERCHANT_CHARGE' => 'array (
  0 => 
  array (
    0 => \'1\',
    1 => \'944\',
  ),
  1 => 
  array (
    0 => \'2\',
    1 => \'566\',
  ),
  2 => 
  array (
    0 => \'3\',
    1 => \'566\',
  ),
)',
  'MERCHANT_ENJOY' => 'array (
  0 => \'1、水电费加思考的风景\',
)',
  'SETTING_REGISTER_VERIFY_ENABLE' => 'array (
  0 => \'2\',
)',
  'SITE_COMPLAIN_QQ' => '88888888',
  'SETTING_REGISTER_ENABLE' => 'array (
  0 => \'1\',
  1 => \'2\',
)',
  'TENGXUN' => 'http://baidu.com',
  'XINLANG' => 'http://baidu.com',
  'SITE_LOGO_FU' => '/uploadfile/2018/0815/20180815072014394.png',
  'SITE_LOGO_ZHU' => '/uploadfile/2018/0815/20180815072017715.png',
  'SITE_MAP_IMAGE' => '/uploadfile/2015/0121/20150121112606476.jpg',
  'REWRITE_RULE' => 'array (
  \'enabled\' => \'1\',
  \'category\' => \'/category/\',
  \'all\' => \'/all/\',
  \'rebate\' => \'/rebate/\',
  \'trial\' => \'/trial/\',
  \'postal\' => \'/postal/\',
  \'commission\' => \'\',
  \'shop/lists\' => \'/shop/\',
  \'shop/show\' => \'/report/\',
)',
  'SITE_WORK_DAY' => '周一至周日：08：00-22：00',
  'SITE_CONSULT_QQ' => '88888888',
  'SITE_COLLABORATE_QQ' => '88888888',
  'SITE_SERVICE_QQ' => '88888888',
  'SITE_CONTACT_ZIPCODE' => '409100',
  'SCORE_SEO' => 'array (
  \'score_title\' => \'积分商城—众多商品等您用积分来兑-{site_title}\',
  \'score_keyword\' => \'积分商城,积分兑换,积分购物,获取积分，Adalways试用系统,试用，试，免费\',
  \'score_description\' => \'{site_title},积分商城,万件商品免费兑换,您可以通过做任务,挣积分,签到挣积分,参与网站其他活动挣积分，Adalways试用系统\',
)',
  'REBATE_SEO' => 'array (
  \'rebate_title\' => \'购物返利商品列表-{site_title}，演示网站\',
  \'rebate_keyword\' => \' 购物返利,划算精品,返利频道，列表页关键词\',
  \'rebate_description\' => \'{site_title}，最新返利商品上线,每天十点更新,全场商品0.1到3折还包邮,划算商品随时追加,购物返现高达50%以上,比聚划算都还省！描述请修改\',
)',
  'HELP_SEO' => 'array (
  \'help_title\' => \'{title}-{site_title}帮助中心\',
  \'help_keyword\' => \'{title}，帮助中心，演示\',
  \'help_description\' => \'{title},{site_title}帮助中心为您解答网站当中任何问题，演示\',
)',
  'ACTIVITY_SEO' => 'array (
  \'activity_title\' => \'系统商家活动报名-{site_title}\',
  \'activity_keyword\' => \'活动报名关键词\',
  \'activity_description\' => \'活动报名介绍\',
)',
  'TRIAL_SEO' => 'array (
  \'trial_title\' => \'免费试用商品列表 - 试用专区_红包试用_精选万件商品免费试用-{site_title}\',
  \'trial_keyword\' => \'免费试用,试用网,试客,试客网,试客网站,红包试用,佣金试用,{site_title}。\',
  \'trial_description\' => \'欢迎来{site_title}:{site_title}—是全国领先的免费试用网和试客网,深的消费者信赖的免费试用网和试客网站,是试客免费试用网和试客网站的首选,{site_title}免费试用网为试客提供最优质和实用的优秀免费试用商品,每天更新,还有红包任务等你来拿。\',
)',
  'POSTAL_SEO' => 'array (
  \'postal_title\' => \'九块九包邮商品列表 - 限时折扣,品牌折扣店-{site_title}\',
  \'postal_keyword\' => \'折扣商品,超低折扣商品,低折扣商品,1折商品,9.9包邮,19.9包邮,特价商品。\',
  \'postal_description\' => \'全场折扣商品均由职业买手从淘宝精选砍价而来,每天10点开抢-速度来抢购。\',
)',
  'SHAI_SEO' => 'array (
  \'shai_title\' => \'买家晒单,分享您的精彩购物之旅-{site_title}\',
  \'shai_keyword\' => \'晒单分享,购物分享,买家晒单，{site_title}。\',
  \'shai_description\' => \'晒单分享,分享真实客观的购物晒单,与试客达人一起发现平台精品,享受真实折扣,交流抢购心得,还可以获得更多免费试用机会,成为最会省钱的划算达人。{site_title}\',
)',
  'REPORT_SEO' => 'array (
  \'report_title\' => \'试用报告列表-{site_title}\',
  \'report_keyword\' => \'买家试用,{site_title}\',
  \'report_description\' => \'买家试用，分享试用体验{site_title}。\',
)',
  'REBATE_SHOW' => 'array (
  \'show_rebate_title\' => \'{title}-{site_title}\',
  \'show_rebate_keyword\' => \'{title},返利频道,{site_title}。\',
  \'show_rebate_description\' => \'{site_title},{title}折超低价,真的很划算。\',
)',
  'TRIAL_SHOW' => 'array (
  \'show_trial_title\' => \'{title}[免费试用]-{site_title}\',
  \'show_trial_keyword\' => \'{title},{site_title}试用专区,{site_title}.\',
  \'show_trial_description\' => \'{title}0元试用,真正的免费试用,即刻申请,数量有限,注册{site_title}买家会员,现在即可在线申请,通过率高。\',
)',
  'POSTAL_SHOW' => 'array (
  \'show_postal_title\' => \'{title}9.9包邮-{site_title}\',
  \'show_postal_keyword\' => \'{title},{site_title}折扣专区,{site_title}.\',
  \'show_postal_description\' => \'{title},从未有过的超低折扣,时间有限,数量有限,赶紧抢购。\',
)',
  'ALL_SEO' => 'array (
  \'all_title\' => \'商品总汇,汇集万件活动商品--{site_title}\',
  \'all_keyword\' => \'商品总汇,免费试用商品,购物返利商品,超低折扣商品,{site_title}。\',
  \'all_description\' => \'{site_title}商品总汇,所有精品,全部商品0.1~3折,万件商品免费试用,折扣真实,试用通过率高,品质保障,平均返现高达50%以上！\',
)',
  'RED_SEO' => 'array (
  \'red_title\' => \'商品总汇_试用专区_红包试用_精选万件商品免费试用--{site_title}\',
  \'red_keyword\' => \'免费试用,试用网,试客,试客网,试客网站,红包试用,佣金试用,{site_title}\',
  \'red_description\' => \'欢迎来{site_title}:{site_title}—是全国领先的免费试用网和试客网,深的消费者信赖的免费试用网和试客网站,是试客免费试用网和试客网站的首选,{site_title}免费试用网为试客提供最优质和实用的优秀免费试用商品,每天更新,还有红包任务等你来拿\',
)',
  'BIND_TB_NUMS' => '5',
  'BIND_SAFE_GRADE' => 'array (
  \'safe\' => \'1\',
)',
  'BUYER_QQ_GROUP' => '88888888',
  'MERCHANT_QQ_GROUP' => '88888888',
  'MERCHANT_CODE' => '',
  'BUYER_CODE' => '',
  'SITE_WEB_NOTICE' => '1',
);	 ?>